### ISSUE TITLE
Example code does not give the same result as the website

### ISSUE THREAD

**Issue by nikclayton** [nikolajbech/underwater-image-color-correction#1]
Following the example code on this image:

![frame-1](https://user-images.githubusercontent.com/773100/69007259-f799e580-093b-11ea-9a99-e51d87e7bc82.png)

results in this image:

![frame-1-fixed](https://user-images.githubusercontent.com/773100/69007262-04b6d480-093c-11ea-8a56-05cff7ca6446.png)

Note the excess blue in the middle, and the fringing around the items at the bottom of the frame. Uploading the same image to https://colorcorrection.firebaseapp.com/ doesn't have the same problem.

Here's the code I used to produce the second frame:

```javascript
const fs = require("fs");
const PNG = require("pngjs").PNG;
const getColorFilterMatrix = require("underwater-image-color-correction");

fs.createReadStream("frame-1.png")
  .pipe(new PNG())
  .on("parsed", function () {
    const filter = getColorFilterMatrix(this.data, this.width, this.height);

    for (let y = 0; y < this.height; y++) {
      for (let x = 0; x < this.width; x++) {
        const i = (this.width * y + x) << 2;
        this.data[i] =
          this.data[i] * filter[0] +
          this.data[i + 1] * filter[1] +
          this.data[i + 2] * filter[2] +
          filter[4] * 255; // Red
        this.data[i + 1] = this.data[i + 1] * filter[6] + filter[9] * 255; // Green
        this.data[i + 2] = this.data[i + 2] * filter[12] + filter[14] * 255; // Blue
      }
    }

    this.pack().pipe(fs.createWriteStream("frame-1-fixed.png"));
  });
```

**Comment by nikolajbech** [comment]
This is a good example of images it's not optimized for at the moment. The image have very little information in the red channel, but have an average red that above the threshold in the algorithm. If more information is taken for the green channel, it will result in a better looking image. I will try to optimize the code for this situation. You can see the "correct" correction here: 
![image](https://user-images.githubusercontent.com/42967687/69055830-01404d80-0a0f-11ea-8209-45d3a9ca0e5a.png)

**Comment by nikclayton** [comment]
Right -- so colorcorrection.firebaseapp.com isn't using the same algorithm as here then? That was the source of my confusion.

**Comment by JCnate** [comment]
Just a hobbyist here, but how did you achieve the "correct" correction?

**Comment by nsmason** [comment]
Just a hobbyist here, but how did you achieve the "correct" correction?

**Comment by alteoxCOM** [comment]
Hi, I would also like to know how you achieve the "correct" correction.. any updates?

Thank you :=)

**Comment by marcobonato** [comment]
> Right -- so colorcorrection.firebaseapp.com isn't using the same algorithm as here then? That was the source of my confusion.

Hi 
Output image after running this algorithm is still different from the output image of your webpage colorcorrection.firebaseapp.com.

My implementation seems correct, but output it's still to different.

`    
        const getColorFilterMatrix = require('underwater-image-color-correction');
        const pixels = require('image-pixels')
        var savePixels = require("save-pixels")
        var zeros = require("zeros")
        var fs = require('fs');

      async function test() {

      var {data, width, height} = await pixels('/Users/admin/Downloads/turtle.jpeg')

      var filter = getColorFilterMatrix(data, width, height);

      for (var i = 0; i < data.length; i += 4) {
        data[i] = data[i] * filter[0] + data[i + 1] * filter[1] + data[i + 2] * filter[2] + filter[4] * 255 // Red
        data[i + 1] = data[i + 1] * filter[6] + filter[9] * 255; // Green
        data[i + 2] = data[i + 2] * filter[12] + filter[14] * 255; // Blue
      }

      var output = zeros([width, height, 3]);
      var x = 0;
      var y = 0;

      for (var i = 0; i < data.length; i += 4) {

        var x = Math.floor((i/4)%width); 
        var y = Math.floor((i/4)/width); 

        output.set(x, y, 0, data[i])
        output.set(x, y, 1, data[i+1])
        output.set(x, y, 2, data[i+2])

      }

      var myFile = fs.createWriteStream('/Users/admin/Downloads/turtle_modified.jpeg');
      savePixels(output, "jpeg").pipe(myFile)

      }

      test();
`

colorcorrection.firebaseapp.com isn't using the same algorithm as here right?
Thank you

**Comment by nikolajbech** [comment]
> colorcorrection.firebaseapp.com isn't using the same algorithm as here right?
> Thank you

Hi, try this one:

```javascript
const PNG = require('pngjs').PNG
const getPixels = require('get-pixels')
const getColorFilterMatrix = require('underwater-image-color-correction')
const fs = require('fs')

const filename = "yourimagefile.jpg"

getPixels(filename, function(err, pixels) {
  if(err) { console.log(filename, "Bad image path", filename) }
  const width = pixels.shape[0]
  const height = pixels.shape[1]
  const pixelData = pixels.data

	const filter = getColorFilterMatrix(pixelData, width, height)

	let colorAdjusted = pixelData

	for (var i = 0; i < colorAdjusted.length; i += 4) {
    colorAdjusted[i] = Math.min(255, Math.max(0, colorAdjusted[i] * filter[0] + colorAdjusted[i + 1] * filter[1] + colorAdjusted[i + 2] * filter[2] + filter[4] * 255)) // Red
    colorAdjusted[i + 1] = Math.min(255, Math.max(0, colorAdjusted[i + 1] * filter[6] + filter[9] * 255)) // Green
    colorAdjusted[i + 2] = Math.min(255, Math.max(0, colorAdjusted[i + 2] * filter[12] + filter[14] * 255)) // Blue
	}

	var png = new PNG({
		width: width,
		height: height,
		filterType: 4
	})

	for (var y = 0; y < height; y++) {
		for (var x = 0; x < width; x += 1) {
			var idx = (width * y + x) << 2;
			png.data[idx] = 0 + colorAdjusted[idx];
			png.data[idx+1] = 0 +colorAdjusted[idx+1];
			png.data[idx+2] = 0 +colorAdjusted[idx+2];
			png.data[idx+3] = 0 +colorAdjusted[idx+3];
		}
	}
	png.pack().pipe(fs.createWriteStream(filename + '.png'))
	console.log("Finished")
})
```

**Comment by nikolajbech** [comment]
> Just a hobbyist here, but how did you achieve the "correct" correction?

The contrast for the different color channels is maximized - this results in a "correct" image since the darkest areas in the photo are black and the lightest areas in the photo are white. If the image is taken underwater, this would not be the case. The algorithm just implements a method to detect where these levels should be set.
